### ISSUE TITLE
スマホでの操作性 仮想十字キーか直接タッチか

### ISSUE THREAD

**Issue by narumincho** [narumincho/DESIRED-Route#3]
![smvod](https://user-images.githubusercontent.com/16481886/38406087-6928376a-39ae-11e8-941d-41ddf1c52ff1.png)

フィールでの移動方法は、仮想十字キーか直接タッチか。
## 仮想十字キー
- 利点
  - フィールドに指が重ならない
  - 指の移動範囲が少ないため操作しやすい
- 欠点
  - フィールドの表示領域が小さくなってしまう

## 直接タッチ
- 利点
  - 操作が直感的
- 欠点
  - フィールドが指で隠れてしまう
  - 指を動かす範囲が広くて操作しにくいかも

仮想十字キーを透過してフィールドが見えるようにしても、主人公の位置は上の方でないとな

**Comment by narumincho** [comment]
仮想十字キーの方に決定

**Comment by lllKishlll** [comment]
OK！
