### ISSUE TITLE
ヒロインは歩けない。ではどうすればいい

### ISSUE THREAD

**Issue by narumincho** [narumincho/DESIRED-Route#5]
主人公は冒険の途中歩けないヒロインと出会う。その後はヒロインを連れていくのか置いていくのかわからないが、どういう流れか分からない

**Comment by lllKishlll** [comment]
遅くなってすまん…

ヒロインは歩けない。冒険には連れて行かない。
一人旅でいいかなと思ってる。主人公も喋る系でいきたい。

エンディングで、ヒロインのいる町まで戻ってきて、星の実が存在しないことを報告しに行くタイミングで少し歩ける様になってる

**Comment by narumincho** [comment]
そういうことか。わかった。
